name: bulk_rename
description: A sample command-line application.
version: 1.2.0
# repository: https://github.com/mtravascio/bulk_rename

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  csv: ^6.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
